//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class featured_advertises
    {
        public int Id { get; set; }
        public int AdvertiseId { get; set; }
        public string Text { get; set; }
    
        public virtual advertis advertis { get; set; }
    }
}
