//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReviewHubEntities1 : DbContext
    {
        public ReviewHubEntities1()
            : base("name=ReviewHubEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<advertise_categories> advertise_categories { get; set; }
        public virtual DbSet<advertise_comments> advertise_comments { get; set; }
        public virtual DbSet<advertise_locations> advertise_locations { get; set; }
        public virtual DbSet<advertise_reacts> advertise_reacts { get; set; }
        public virtual DbSet<advertiser> advertisers { get; set; }
        public virtual DbSet<advertis> advertises { get; set; }
        public virtual DbSet<company_categories> company_categories { get; set; }
        public virtual DbSet<review_comments> review_comments { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user_locations> user_locations { get; set; }
        public virtual DbSet<user_types> user_types { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<review_reacts> review_reacts { get; set; }
    }
}
